custom_stat_map = {
    'Exchangeable:': 'Exchangeable:',
    'Compatible with:': 'Compatible with:',
    '% Critical Hit bonus on the spell': '% Critical Hit bonus on the spell',
    "Increases the spell's maximum range by": "Increases the spell's maximum range by",
    'no longer requires a line of sight': 'no longer requires a line of sight',
    "Reduces the spell's cooldown period by": "Reduces the spell's cooldown period by",
    "Reduces the spell's AP cost by": "Reduces the spell's AP cost by",
    'Increases the maximum number of times can be cast per turn by': 'Increases the maximum number of times can be cast per turn by',
    'Effectiveness:': 'Effectiveness:', 'Paddock Item': 'Paddock Item', 'Remaining uses:/': 'Remaining uses:/', 'HP': 'HP', '(Water damage)': '(Water damage)', 'Title:': 'Title:', '(Neutral damage)': '(Neutral damage)', '(Air steal)': '(Air steal)', '(Water steal)': '(Water steal)', '(Fire damage)': '(Fire damage)', '(Air damage)': '(Air damage)', 'Teleport': 'Teleport', 'Different area to:': 'Different area to:', 'Alignment level': 'Alignment level', 'Restores energy points': 'Restores energy points', '(Fire steal)': '(Fire steal)', '(HP restored)': '(HP restored)', 'Set bonus': 'Set bonus', 'Learn the spell level': 'Learn the spell level', 'XP': 'XP', "What's in there?": "What's in there?", 'emote': 'emote', 'Be level or higher': 'Be level or higher', 'Positions the compass': 'Positions the compass', 'No future smithmagic': 'No future smithmagic', '% chance of success': '% chance of success', 'Cooperative crafting impossible': 'Cooperative crafting impossible', 'Received on': 'Received on', '(Earth damage)': '(Earth damage)', 'remaining fight(s)': 'remaining fight(s)', 'Get on/off a mount': 'Get on/off a mount', 'Summons a level': 'Summons a level', 'Begins a quest': 'Begins a quest', 'Wrapped by:': 'Wrapped by:', 'Linked to the character': 'Linked to the character', 'Have a mount equipped': 'Have a mount equipped', ' not equipped': ' not equipped', 'Change the attack element': 'Change the attack element', 'Hunting weapon': 'Hunting weapon', 'Frees an enemy soul': 'Frees an enemy soul', 'Learn the spell': 'Learn the spell', 'Subscribers only': 'Subscribers only', 'Level Incarnation': 'Level Incarnation', 'Emote': 'Emote', 'Teleport to save point': 'Teleport to save point', 'is no longer linear': 'is no longer linear', "Someone's following you!": "Someone's following you!", 'Last fed -': 'Last fed -', 'Forget one level of the spell': 'Forget one level of the spell', 'kama gain': 'kama gain', 'Damage on the spell:': 'Damage on the spell:', '(Earth steal)': '(Earth steal)', '(Neutral steal)': '(Neutral steal)', 'Frees enemy souls': 'Frees enemy souls', 'Revive the target': 'Revive the target', 'Trap Damage': 'Trap Damage', 'Seeks': 'Seeks',
    'Name:': 'Name:', 'Ornament:': 'Ornament:', 'Increases the maximum number of times can be cast per target by': 'Increases the maximum number of times can be cast per target by', 'Changes appearance': 'Changes appearance', "Makes the spell's range modifiable": "Makes the spell's range modifiable", 'Changes speech': 'Changes speech', "Increases's basic damage by": "Increases's basic damage by", 'Heal': 'Heal', '% chance of capturing a mount': '% chance of capturing a mount', 'Number of victims:': 'Number of victims:', 'Get a mount!': 'Get a mount!', 'Reflects damage': 'Reflects damage', 'level': 'level', '% chance of capturing a power soul': '% chance of capturing a power soul', 'Legendary Status': 'Legendary Status', 'Starts a fight against': 'Starts a fight against', 'Applies a% experience bonus to professions for minutes': 'Applies a% experience bonus to professions for minutes', 'Applies an experience bonus of% for minutes': 'Applies an experience bonus of% for minutes', 'Reinitialise the effects of an item with a level equal to or less than': 'Reinitialise the effects of an item with a level equal to or less than', 'Experience:': 'Experience:', 'Steals kamas': 'Steals kamas', 'Place a prism': 'Place a prism', 'Teleport to the nearest allied prism': 'Teleport to the nearest allied prism', 'Rename the alliance': 'Rename the alliance', 'Prepares scrolls': 'Prepares scrolls', "Write a character's name": "Write a character's name", 'Switches alignment': 'Switches alignment', 'Globally Pre-Sentient': 'Globally Pre-Sentient', "Change the alliance's emblem": "Change the alliance's emblem", 'Resuscitates allies on your map': 'Resuscitates allies on your map', "Change the guild's emblem": "Change the guild's emblem", 'Add a temporary spell': 'Add a temporary spell', 'Earth Resistance in PvP': 'Earth Resistance in PvP', 'Neutral Resistance in PvP': 'Neutral Resistance in PvP', 'Water Resistance in PvP': 'Water Resistance in PvP', 'Fire Resistance in PvP': 'Fire Resistance in PvP', 'Air Resistance in PvP': 'Air Resistance in PvP', '% Air Resistance in PvP': '% Air Resistance in PvP', '% Water Resistance in PvP': '% Water Resistance in PvP', '% Fire Resistance in PvP': '% Fire Resistance in PvP', '% Neutral Resistance in PvP': '% Neutral Resistance in PvP', '% Earth Resistance in PvP': '% Earth Resistance in PvP', 'Remove an item from a Paddock': 'Remove an item from a Paddock', 'Size: cells': 'Size: cells', 'Use custom set n°': 'Use custom set n°', 'Summons a Perceptor': 'Summons a Perceptor', 'Rename the guild': 'Rename the guild', 'Rename guild:': 'Rename guild:', 'Get a divorce': 'Get a divorce', '-special spell-': '-special spell-', 'The spell can be cast on a free cell': 'The spell can be cast on a free cell'
}

print(custom_stat_map['Exchangeable'])
